name: Spring Boot Java Web App with Code Coverage

on:
  push:
    branches:
      - master
env:  
  JAVA_VERSION: '8'
  MAVEN_RUN_COMMAND: mvn -B package --file pom.xml -Dmaven.test.skip=true
  AZURE_WEBAPP: 'new-javaapp'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}
    
        
    - name: Build with the Maven
      run: ${{ env.MAVEN_RUN_COMMAND }}
      
    - name: Testing
      run: mvn clean test
      
    - name: Package
      run: mvn -B clean package
      
    - name: Mvn verify
      run: mvn -B clean verify -DskipTests
  
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'
  
    - run: mvn -B verify -P coverage --no-transfer-progress

    - uses: codecov/codecov-action@v1
      with:
        file: ./**/target/site/jacoco/jacoco.xml
        name: codecov

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: java-app
    
   
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: '.'
